### ISSUE TITLE
disk: Feature http://lv2plug.in/ns/ext/state#makePath is not supported

### ISSUE THREAD

**Issue by magnetophon** [OpenMusicKontrollers/eteroj.lv2#1]
I get this message when running in jalv.gtk.

As for the cause, @x42 wrote on IRC:
```
make_path is a feature passed to  state_restore, state_save.  not instantiate
```

**Comment by x42** [comment]
According to http://lv2plug.in/ns/ext/state/#makePath a host can do both. Ardour passes it via instantiate, jalv only to the state methods.

**Comment by ventosus** [comment]
@magnetophon this is actually a bug in jalv. eteroj#disk requires this feature [1], so a host not supporting it (here jalv) should not try to load it in the first place.

I need a file path to stream events to disk from start (e.g. in instantiate). I could stream to a tempfile and then upon state#save copy the file, but LV2 plugins should not save anything outside their allotted disk space.

Don't see the best way to fix this, yet

[1] https://github.com/OpenMusicKontrollers/eteroj.lv2/blob/master/eteroj.ttl#L144

**Comment by magnetophon** [comment]
Sorry for responding so late, this one fell trough the cracks.

@x42 Do you have any ideas for a fix?

**Comment by x42** [comment]
jalv? that's @drobilla territory.

**Comment by ventosus** [comment]
@magnetophon the eteroj:disk plugin has been deprecated in version 0.6.0, so there won't be any fix needed.

**Comment by drobilla** [comment]
A very long time ago (nearly a decade) Jalv didn't refuse to instantiate plugins that required features it does not support, but that shouldn't be the case now.  If not, please file an issue.

Re: passing makePath in those places, both are valid but they have different use cases.
